apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    # Logging
    logs:
      general:
        level: DEBUG
    
    # Persistence for ACME (SSL certificates)
    persistence:
      enabled: true
      path: /acme
      size: 128Mi
    
    # Let's Encrypt arguments
    additionalArguments:
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.storage=/acme/acme.json"
      - "--certificatesresolvers.le.acme.email=$(TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_EMAIL)"
      - "--certificatesresolvers.le.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"

    # Inject Email from Secrets
    env:
      - name: TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_EMAIL
        valueFrom:
          secretKeyRef:
            name: traefik-acme-secret
            key: email
    
    # HTTP -> HTTPS Redirection (Traefik v3 syntax)
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true