apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      # Email берется из переменной окружения
      - "--certificatesresolvers.le.acme.storage=/data/acme.json"
    env:
      - name: TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_EMAIL
        valueFrom:
          secretKeyRef:
            name: traefik-acme-secret
            key: email
    ports:
      web:
        redirectTo: websecure