apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-daily-update
spec:
  schedule: "0 4 * * *" # Daily at 4:00 AM
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Release.Name }}-updater
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - kubectl rollout restart deployment/{{ .Release.Name }}
          restartPolicy: OnFailure