apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate # Для Xray лучше Recreate, чтобы не занимать порты дважды
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Release.Name }}-updater
      
      initContainers:
      - name: db-downloader
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo ">>> Downloading Xray Databases..."
            apk add --no-cache wget
            mkdir -p /data
            wget -qO /data/zapret.dat https://github.com/kutovoys/ru_gov_zapret/releases/latest/download/zapret.dat
            wget -qO /data/geoip.dat https://raw.githubusercontent.com/runetfreedom/russia-v2ray-rules-dat/release/geoip.dat
            wget -qO /data/geosite.dat https://raw.githubusercontent.com/runetfreedom/russia-v2ray-rules-dat/release/geosite.dat
        volumeMounts:
        - name: xray-data
          mountPath: /data

      containers:
        - name: website
          image: {{ .Values.website.image }}
          ports:
            - containerPort: 80
              name: http

        - name: remnanode
          image: {{ .Values.node.image }}
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: NODE_PORT
              value: {{ .Values.node.apiPort | quote }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: SECRET_KEY
            - name: XRAY_LOCATION_ASSET
              value: /usr/local/bin
          ports:
            # --- 1. API PORT (Для управления из панели) ---
            - containerPort: {{ .Values.node.apiPort }}
              name: api
              protocol: TCP
              hostPort: {{ .Values.node.apiPort }}

            # --- 2. АВТОМАТИЧЕСКАЯ ГЕНЕРАЦИЯ ПОРТОВ (Inbounds) ---
            {{- range .Values.inbounds }}
            
            # TCP
            - containerPort: {{ .port }}
              name: tcp-{{ .port }}
              protocol: TCP
              {{- if eq .mode "direct" }}
              hostPort: {{ .port }}
              {{- end }}

            # UDP (для direct)
            {{- if eq .mode "direct" }}
            - containerPort: {{ .port }}
              name: udp-{{ .port }}
              protocol: UDP
              hostPort: {{ .port }}
            {{- end }}

            {{- end }}

          volumeMounts:
            - name: xray-data
              mountPath: /usr/local/bin/geoip.dat
              subPath: geoip.dat
            - name: xray-data
              mountPath: /usr/local/bin/geosite.dat
              subPath: geosite.dat
            - name: xray-data
              mountPath: /usr/local/bin/zapret.dat
              subPath: zapret.dat

      volumes:
      - name: xray-data
        emptyDir: {}