apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-ws-headers
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      Upgrade: "websocket"
      Connection: "Upgrade"

---
# 1. Main Website (Fallback/Camouflage)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-web
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.domain }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}
          port: 80
  tls:
    certResolver: le

---
# 2. WebSocket Routing
{{- range .Values.inbounds }}
{{- if eq .mode "ingress-path" }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ $.Values.domain }}`) && PathPrefix(`{{ .path }}`)
      kind: Rule
      middlewares:
        - name: {{ $.Release.Name }}-ws-headers
      services:
        - name: {{ $.Release.Name }}
          port: {{ .port }}
          passHostHeader: true
  tls:
    certResolver: le
---
{{- end }}
{{- end }}

# 3. XHTTP Routing (No WS headers)
{{- range .Values.inbounds }}
{{- if eq .mode "ingress-xhttp" }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ $.Values.domain }}`) && PathPrefix(`{{ .path }}`)
      kind: Rule
      services:
        - name: {{ $.Release.Name }}
          port: {{ .port }}
          passHostHeader: true
  tls:
    certResolver: le
---
{{- end }}
{{- end }}

# 4. gRPC Routing (h2c scheme)
{{- range .Values.inbounds }}
{{- if eq .mode "ingress-grpc" }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ $.Values.domain }}`) && PathPrefix(`/{{ .serviceName }}`)
      kind: Rule
      services:
        - name: {{ $.Release.Name }}
          port: {{ .port }}
          passHostHeader: true
          scheme: h2c
  tls:
    certResolver: le
---
{{- end }}
{{- end }}

# 5. Reality/Trojan (SNI Routing)
{{- range .Values.inbounds }}
{{- if eq .mode "ingress-sni" }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: {{ range $i, $d := .sni }}{{ if $i }} || {{ end }}HostSNI(`{{ $d }}`){{ end }}
      services:
        - name: {{ $.Release.Name }}
          port: {{ .port }}
  tls:
    passthrough: true
---
{{- end }}
{{- end }}