apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-updater
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-restarter
rules:
  # Разрешаем управлять Deployments
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    verbs: ["get", "patch", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-restarter-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-updater
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-restarter
  apiGroup: rbac.authorization.k8s.io