apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 80
      name: http
      targetPort: http
    
    # Добавляем порты, которые идут через Traefik (SNI или Path)
    {{- range .Values.inbounds }}
    {{- if or (eq .mode "ingress-sni") (eq .mode "ingress-path") }}
    - port: {{ .port }}
      name: {{ .name }}
      targetPort: {{ .port }}
    {{- end }}
    {{- end }}