apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 80
      name: http
      targetPort: http
    
    # Expose ports for all Ingress-based modes (SNI, Path, gRPC, XHTTP)
    {{- range .Values.inbounds }}
    {{- if ne .mode "direct" }}
    - port: {{ .port }}
      name: {{ .name }}
      targetPort: {{ .port }}
    {{- end }}
    {{- end }}