website:
  image: th3ro/remnanode_website:latest
  pullPolicy: Always

node:
  image: remnawave/node:latest
  apiPort: 2222

# Главный домен для панели/сайта
domain: "example.com"
email: "admin@example.com"

secretKey: ""

# Типы режимов (mode):
# - ingress-sni:  TCP Passthrough через Traefik (для Reality/Trojan). Требует 'sni'.
# - ingress-path: HTTP/WS роутинг через Traefik (для WebSocket). Требует 'path'.
# - direct:       Прямой доступ (HostPort).

inbounds: []
# Пример структуры для secrets.yaml:
# - name: reality
#   port: 10000        # Порт внутри контейнера
#   mode: ingress      # Работает через Traefik (443)
#   sni:               # Домены для маскировки
#     - google.com
# - name: mixed
#   port: 10001        # Порт внутри и снаружи
#   mode: direct       # Открыт напрямую
#   protocol: TCP      # TCP/UDP